name       : libcacard
version    : 2.5.3
release    : 2
source     :
    - http://www.spice-space.org/download/libcacard/libcacard-2.5.3.tar.xz : 243ff03c563a95faed497db7f524fcb34ccd6f388d1175ecf31c371a3188963b
license    : LGPL-2.1
component  : virt
summary    : library providing emulation of smart cards
description: |
    This library provides emulation of smart cards to a virtual card reader running in a guest virtual machine.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gthread-2.0)
    - pkgconfig(nss)
    - pkgconfig(libpcsclite)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
