name       : libcacard
version    : 2.6.1
release    : 3
source     :
    - http://www.spice-space.org/download/libcacard/libcacard-2.6.1.tar.xz : 6276c6a2bd018bf14f1b97260fff093b4a2325a9177be4fc6be7c1a9e204def0
license    : LGPL-2.1-or-later
component  : virt
summary    : library providing emulation of smart cards
description: |
    This library provides emulation of smart cards to a virtual card reader running in a guest virtual machine.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gthread-2.0)
    - pkgconfig(nss)
    - pkgconfig(libpcsclite)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
