name       : libcacard
version    : 2.5.2
release    : 1
source     :
    - http://www.spice-space.org/download/libcacard/libcacard-2.5.2.tar.xz : 2e39d52346a64af3bd7ee6bff658c4dcfee05a5ab8c0cf70d225fa58d3df4ecb
license    : LGPL-2.1
component  : virt
summary    : library providing emulation of smart cards
description: |
    This library provides emulation of smart cards to a virtual card reader running in a guest virtual machine.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gthread-2.0)
    - pkgconfig(nss)
    - pkgconfig(libpcsclite)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
